<?php

namespace AppBundle\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository{

	public function findAll(){
		$em = $this->getDoctrine()->getManager();

        $query = $em->createQuery('SELECT * FROM `blog` b join users u ON(b.created_by = u.id)');
        $blogs = $query->getResult();
        return $blogs;
    }
}
